mqinstance:
  name: telco-cloud
  namespace: gitops-cp-queue-manager
  spec:
    license:
      accept: true
      license: L-RJON-C7QG3S
      use: NonProduction
    queueManager:
      storage:
        queueManager:
          type: persistent-claim
        defaultClass: ibmc-block-bronze
      name: QM1
      mqsc:
        - configMap:
            name: oms-mq-configmap
            items:
              - config.mqsc
    version: 9.2.4.0-r1
    web:
      enabled: true
configMap:
  name: oms-mq-configmap